version: '3.8'

services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - my_network

  python:
    build:
      context: ./python
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: my_database
      DB_USER: postgres
      DB_PASSWORD: your_password
    networks:
      - my_network

networks:
  my_network: